export const AUTHENTICATION_ACTIONS = {
  GET_AUTH_INFO: 'GET_AUTH_INFO',
  GET_AUTH_INFO_ERROR: 'GET_AUTH_INFO_ERROR',
  LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',
  LOGOUT_RESPONSE_ERROR: 'LOGOUT_RESPONSE_ERROR'
};

export const TASK_ACTIONS = {
  GET_TASKS_RESPONSE: 'GET_TASKS_RESPONSE',
  GET_TASKS_RESPONSE_ERROR: 'GET_TASKS_RESPONSE_ERROR'
};

export const USER_ACTIONS = {
  GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',
  GET_USERS_RESPONSE_ERROR: 'GET_USERS_RESPONSE_ERROR'
};
